version: '2'
services:
    noautocomplete-app:
        image: noautocomplete
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://noautocomplete-postgresql:5432/noautocomplete
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    noautocomplete-postgresql:
        extends:
            file: postgresql.yml
            service: noautocomplete-postgresql
