version: '2'
services:
    jacksonviews-app:
        image: jacksonviews
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jacksonviews-postgresql:5432/jacksonviews
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jacksonviews-postgresql:
        extends:
            file: postgresql.yml
            service: jacksonviews-postgresql
