version: '2'
services:
    autocompletedtooptim-app:
        image: autocompletedtooptim
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://autocompletedtooptim-postgresql:5432/autocompletedtooptim
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    autocompletedtooptim-postgresql:
        extends:
            file: postgresql.yml
            service: autocompletedtooptim-postgresql
