version: '2'
services:
    autocompletedtooptim-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/autocompletedtooptim/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=autocompletedtooptim
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
